import { AUTHORS, PERIODS, WORKS, type Period, type TimelineItem } from "./data";

type AuthorRow = [string, string, number, number, boolean?];
type WorkRow = [string, string, string, number, string?];

const authorRows: AuthorRow[] = [
  ["anonymous-gilgames", "Anonymní mezopotámská literatura", -2000, -1700],
  ["anonymous-bible", "Biblické texty", -1200, 100],
  ["anonymous-roland", "Anonymní francouzská epika", 1000, 1150],
  ["anonymous-kristian", "Anonymní české legendy", 950, 1050],
  ["anonymous-hospodine", "Staroslověnská a raně česká tvorba", 900, 1100],
  ["anonymous-alexandreida", "Anonymní česká epika", 1250, 1350],
  ["anonymous-dalimil", "Anonymní české kroniky", 1280, 1350],
  ["anonymous-mastickar", "Anonymní středověké drama", 1300, 1400],
  ["anonymous-podkoni", "Anonymní česká satira", 1350, 1450],
  ["aesop", "Ezop", -620, -564],
  ["kosmas", "Kosmas", 1045, 1125],
  ["jan-hus", "Jan Hus", 1370, 1415],
  ["vaclav-hajek", "Václav Hájek z Libočan", 1499, 1553],
  ["bedrich-bridel", "Bedřich Bridel", 1619, 1680],
  ["byron", "George Gordon Byron", 1788, 1824],
  ["zola", "Émile Zola", 1840, 1902],
  ["rimbaud", "Arthur Rimbaud", 1854, 1891],
  ["dobrovsky", "Josef Dobrovský", 1753, 1829],
  ["jungmann", "Josef Jungmann", 1773, 1847],
  ["celakovsky", "František Ladislav Čelakovský", 1799, 1852],
  ["tyl", "Josef Kajetán Tyl", 1808, 1856],
  ["nemcova", "Božena Němcová", 1820, 1862],
  ["neruda", "Jan Neruda", 1834, 1891],
  ["sladek", "Josef Václav Sládek", 1845, 1912],
  ["svatopluk-cech", "Svatopluk Čech", 1846, 1908],
  ["jirasek", "Alois Jirásek", 1851, 1930],
  ["vrchlicky", "Jaroslav Vrchlický", 1853, 1912],
  ["vilem-mrstik", "Vilém Mrštík", 1863, 1912],
  ["alois-mrstik", "Alois Mrštík", 1861, 1925],
  ["maupassant", "Guy de Maupassant", 1850, 1893],
  ["slejhar", "Josef Karel Šlejhar", 1864, 1914],
  ["apollinaire", "Guillaume Apollinaire", 1880, 1918],
  ["pasternak", "Boris Pasternak", 1890, 1960],
  ["tennessee-williams", "Tennessee Williams", 1911, 1983],
  ["solzhenitsyn", "Alexandr Solženicyn", 1918, 2008],
  ["durrenmatt", "Friedrich Dürrenmatt", 1921, 1990],
  ["antonin-sova", "Antonín Sova", 1864, 1928],
  ["bezruc", "Petr Bezruč", 1867, 1958],
  ["brezina", "Otokar Březina", 1868, 1929],
  ["sk-neumann", "Stanislav Kostka Neumann", 1875, 1947],
  ["viktor-dyk", "Viktor Dyk", 1877, 1931],
  ["frana-sramek", "Fráňa Šrámek", 1877, 1952],
  ["olbracht", "Ivan Olbracht", 1882, 1952],
  ["hasek", "Jaroslav Hašek", 1883, 1923],
  ["durych", "Jaroslav Durych", 1886, 1962],
  ["vancura", "Vladislav Vančura", 1891, 1942],
  ["jaroslav-havlicek", "Jaroslav Havlíček", 1896, 1943],
  ["wolker", "Jiří Wolker", 1900, 1924],
  ["seifert", "Jaroslav Seifert", 1901, 1986],
  ["halas", "František Halas", 1901, 1949],
  ["holan", "Vladimír Holan", 1905, 1980],
  ["werich", "Jan Werich", 1905, 1980],
  ["voskovec", "Jiří Voskovec", 1905, 1981],
  ["hrubin", "František Hrubín", 1910, 1971],
  ["jiri-kolar", "Jiří Kolář", 1914, 2002],
  ["hrabal", "Bohumil Hrabal", 1914, 1997],
  ["orten", "Jiří Orten", 1919, 1941],
  ["legatova", "Květa Legátová", 1919, 2012],
  ["skacel", "Jan Skácel", 1922, 1989],
  ["fuks", "Ladislav Fuks", 1923, 1994],
  ["skvorecky", "Josef Škvorecký", 1924, 2012],
  ["lustig", "Arnošt Lustig", 1926, 2011],
  ["vaculik", "Ludvík Vaculík", 1926, 2015],
  ["kohout", "Pavel Kohout", 1928, 2026, true],
  ["smoljak", "Ladislav Smoljak", 1931, 2010],
  ["paral", "Vladimír Páral", 1932, 2026, true],
  ["josef-topol", "Josef Topol", 1935, 2015],
  ["sverak", "Zdeněk Svěrák", 1936, 2026, true],
  ["havel", "Václav Havel", 1936, 2011],
  ["fitzgerald", "Francis Scott Fitzgerald", 1896, 1940],
  ["kerouac", "Jack Kerouac", 1922, 1969],
  ["robert-merle", "Robert Merle", 1908, 2004],
  ["styron", "William Styron", 1925, 2006],
  ["karel-polacek", "Karel Poláček", 1892, 1945],
  ["viewegh", "Michal Viewegh", 1962, 2026, true],
  ["lednicka", "Karin Lednická", 1969, 2026, true],
];

const workRows: WorkRow[] = [
  ["epos-gilgames", "anonymous-gilgames", "Epos o Gilgamešovi", -1800],
  ["bible", "anonymous-bible", "Bible", 100],
  ["song-roland", "anonymous-roland", "Píseň o Rolandovi", 1100],
  ["kristianova-legenda", "anonymous-kristian", "Kristiánova legenda", 993],
  ["hospodine-pomiluj", "anonymous-hospodine", "Hospodine, pomiluj ny", 1050],
  ["kosmova-kronika", "kosmas", "Kronika Čechů", 1125, "Kosmova kronika"],
  ["alexandreida", "anonymous-alexandreida", "Alexandreida", 1300],
  ["dalimilova-kronika", "anonymous-dalimil", "Kronika tak řečeného Dalimila", 1314, "Dalimilova kronika"],
  ["mastickar", "anonymous-mastickar", "Mastičkář", 1350],
  ["podkoni-zak", "anonymous-podkoni", "Podkoní a žák", 1400],
  ["de-ecclesia", "jan-hus", "O církvi", 1413, "De ecclesia"],
  ["kronika-ceska", "vaclav-hajek", "Kronika česká", 1541],
  ["co-buh-clovek", "bedrich-bridel", "Co Bůh? Člověk?", 1659],
  ["childe-harold", "byron", "Childe Haroldova pouť", 1812],
  ["germinal", "zola", "Germinal", 1885],
  ["opily-korab", "rimbaud", "Opilý koráb", 1871],
  ["dejiny-reci", "dobrovsky", "Dějiny české řeči a literatury", 1792, "Josef Dobrovský"],
  ["slovnik-jungmann", "jungmann", "Slovník česko-německý", 1835, "Slovník česko-německý Josefa Jungmanna"],
  ["ohlas-ceskych", "celakovsky", "Ohlas písní českých", 1839],
  ["strakonicky-dudak", "tyl", "Strakonický dudák", 1847],
  ["babicka", "nemcova", "Babička", 1855],
  ["diva-bara", "nemcova", "Divá Bára", 1856],
  ["povidky-malostranske", "neruda", "Povídky malostranské", 1878],
  ["novy-broucek", "svatopluk-cech", "Nový epochální výlet pana Broučka", 1888],
  ["stare-povesti", "jirasek", "Staré pověsti české", 1894],
  ["noc-karlstejn", "vrchlicky", "Noc na Karlštejně", 1884],
  ["marysa", "vilem-mrstik", "Maryša", 1894],
  ["kulicka", "maupassant", "Kulička", 1880, "Kulička (Maupassant)"],
  ["kure-melancholik", "slejhar", "Kuře melancholik", 1889],
  ["alkoholy", "apollinaire", "Alkoholy", 1913],
  ["pasmo", "apollinaire", "Pásmo", 1913, "Pásmo (Apollinaire)"],
  ["doktor-zivago", "pasternak", "Doktor Živago", 1957],
  ["tramvaj-touha", "tennessee-williams", "Tramvaj do stanice Touha", 1947],
  ["jeden-den", "solzhenitsyn", "Jeden den Ivana Děnisoviče", 1962],
  ["navsteva-stare-damy", "durrenmatt", "Návštěva staré dámy", 1956],
  ["kvety-intimnich", "antonin-sova", "Květy intimních nálad", 1891],
  ["slezske-pisne", "bezruc", "Slezské písně", 1909],
  ["tajemne-dalky", "brezina", "Tajemné dálky", 1895],
  ["nove-zpevy", "sk-neumann", "Nové zpěvy", 1918],
  ["krysar", "viktor-dyk", "Krysař", 1915],
  ["stribrny-vitr", "frana-sramek", "Stříbrný vítr", 1910],
  ["nikola-suhaj", "olbracht", "Nikola Šuhaj loupežník", 1933],
  ["svejk", "hasek", "Osudy dobrého vojáka Švejka", 1921, "Osudy dobrého vojáka Švejka za světové války"],
  ["bloudeni", "durych", "Bloudění", 1929, "Bloudění (román)"],
  ["rozmarne-leto", "vancura", "Rozmarné léto", 1926],
  ["petrolejove-lampy", "jaroslav-havlicek", "Petrolejové lampy", 1935],
  ["tezka-hodina", "wolker", "Těžká hodina", 1922],
  ["maminka", "seifert", "Maminka", 1954, "Maminka (sbírka)"],
  ["torzo-nadeje", "halas", "Torzo naděje", 1938],
  ["noc-s-hamletem", "holan", "Noc s Hamletem", 1964],
  ["vest-pocket", "werich", "Vest pocket revue", 1927],
  ["romance-kridlovku", "hrubin", "Romance pro křídlovku", 1962],
  ["prometheova-jatra", "jiri-kolar", "Prométheova játra", 1950],
  ["ostre-sledovane", "hrabal", "Ostře sledované vlaky", 1965],
  ["obsluhoval-kral", "hrabal", "Obsluhoval jsem anglického krále", 1971],
  ["elegie-orten", "orten", "Elegie", 1946, "Elegie (Jiří Orten)"],
  ["smutenka", "skacel", "Smuténka", 1965],
  ["spalovac", "fuks", "Spalovač mrtvol", 1967],
  ["zbabelci", "skvorecky", "Zbabělci", 1958],
  ["prima-sezona", "skvorecky", "Prima sezóna", 1975],
  ["modlitba-katerinu", "lustig", "Modlitba pro Kateřinu Horovitzovou", 1964],
  ["sekyra", "vaculik", "Sekyra", 1966, "Sekyra (román)"],
  ["katyne", "kohout", "Katyně", 1978, "Katyně (román)"],
  ["dobyti-polu", "sverak", "Dobytí severního pólu", 1985],
  ["soukroma-vichrice", "paral", "Soukromá vichřice", 1966],
  ["konec-masopustu", "josef-topol", "Konec masopustu", 1963],
  ["audience", "havel", "Audience", 1975],
  ["jeptiska", "diderot", "Jeptiška", 1796, "Jeptiška (román)"],
  ["lakomec", "moliere", "Lakomec", 1668],
  ["rozum-cit", "austen", "Rozum a cit", 1811],
  ["revizor", "gogol", "Revizor", 1836, "Revizor (Gogol)"],
  ["kral-lavra", "borovsky", "Král Lávra", 1854],
  ["jama-kyvadlo-list", "poe", "Jáma a kyvadlo a jiné povídky", 1842, "Jáma a kyvadlo"],
  ["dorian-gray", "wilde", "Obraz Doriana Graye", 1890],
  ["zabijak", "zola", "Zabiják", 1877, "Zabiják (román)"],
  ["cekani-godot", "beckett", "Čekání na Godota", 1952],
  ["alchymista-school", "coelho", "Alchymista", 1988, "Alchymista (román)"],
  ["great-gatsby", "fitzgerald", "Velký Gatsby", 1925],
  ["anne-diary", "anne-frank", "Deník Anne Frankové", 1947],
  ["old-man-sea", "hemingway", "Stařec a moře", 1952],
  ["on-road", "kerouac", "Na cestě", 1957],
  ["death-trade", "robert-merle", "Smrt je mým řemeslem", 1952],
  ["animal-farm", "orwell", "Farma zvířat", 1945],
  ["western-front", "remarque", "Na západní frontě klid", 1929],
  ["petr-lucie", "rolland", "Petr a Lucie", 1920],
  ["mice-men", "steinbeck", "O myších a lidech", 1937],
  ["sophies-choice", "styron", "Sophiina volba", 1979],
  ["hobbit", "tolkien", "Hobit", 1937],
  ["bylo-nas-pet", "karel-polacek", "Bylo nás pět", 1946],
  ["bajecna-leta", "viewegh", "Báječná léta pod psa", 1992],
  ["bila-nemoc", "capek", "Bílá nemoc", 1937],
  ["smesne-lasky", "kundera", "Směšné lásky", 1963],
  ["jozova-hanule", "legatova", "Jozova Hanule", 2002],
  ["edison", "nezval", "Edison", 1928, "Edison (báseň)"],
  ["smrt-srncu", "ota-pavel", "Smrt krásných srnců", 1971],
  ["hana", "mornstajnova", "Hana", 2017, "Hana (román)"],
  ["sikmy-kostel", "lednicka", "Šikmý kostel", 2020],
];

export const CURRICULUM_AUTHORS: TimelineItem[] = authorRows.map(([id, title, start, end, living = false]) => ({
  id, title, start, end, living, lane: "authors", kind: "author", importance: 5, wikiTitle: title,
  summary: "Autor zahrnutý v dodaných maturitních a školních materiálech.", tags: ["CERMAT", "maturita"],
}));
export const CURRICULUM_WORKS: TimelineItem[] = workRows.map(([id, authorId, title, year, wikiTitle = title]) => ({
  id, authorId, title, start: year, end: year, lane: "works", kind: "work", importance: 4, wikiTitle,
  summary: "Dílo zahrnuté v dodaných školních nebo maturitních materiálech.", tags: ["maturita"],
}));

export const CURRICULUM_PERIODS: Period[] = [
  { id: "cermat-antika", title: "Antika", start: -800, end: 500, row: 0, scope: "world", color: "#7c6a45", wikiTitle: "Antika" },
  { id: "cermat-stredovek", title: "Středověk", start: 500, end: 1500, row: 0, scope: "world", color: "#63738c", wikiTitle: "Středověk" },
  { id: "cermat-renesance", title: "Renesance a humanismus", start: 1350, end: 1600, row: 1, scope: "world", color: "#9a7644", wikiTitle: "Renesance" },
  { id: "cermat-baroko", title: "Baroko", start: 1600, end: 1750, row: 1, scope: "world", color: "#8c5a45", wikiTitle: "Baroko" },
  { id: "cermat-klasicismus", title: "Klasicismus a osvícenství", start: 1650, end: 1800, row: 1, scope: "world", color: "#9a895b", wikiTitle: "Klasicismus" },
  { id: "cermat-romantismus", title: "Preromantismus a romantismus", start: 1760, end: 1850, row: 1, scope: "world", color: "#7a5c91", wikiTitle: "Romantismus" },
  { id: "cermat-realismus", title: "Realismus a naturalismus", start: 1830, end: 1900, row: 1, scope: "world", color: "#668068", wikiTitle: "Realismus (umění)" },
  { id: "cermat-moderna", title: "Literární moderna", start: 1880, end: 1914, row: 1, scope: "world", color: "#586f8e", wikiTitle: "Literární moderna" },
  { id: "cermat-avantgarda", title: "Modernismus a avantgarda", start: 1900, end: 1945, row: 1, scope: "world", color: "#9b5f4b", wikiTitle: "Avantgarda" },
  { id: "cermat-existencialismus", title: "Existencialismus", start: 1930, end: 1965, row: 3, scope: "world", color: "#5f6176", wikiTitle: "Existencialismus" },
  { id: "cermat-socialisticky-realismus", title: "Socialistický realismus", start: 1932, end: 1989, row: 3, scope: "world", color: "#a54f4f", wikiTitle: "Socialistický realismus" },
  { id: "cermat-magicky-realismus", title: "Magický realismus", start: 1940, end: 2000, row: 3, scope: "world", color: "#4e8a78", wikiTitle: "Magický realismus" },
  { id: "cermat-absurdni-drama", title: "Absurdní drama", start: 1950, end: 1980, row: 3, scope: "world", color: "#745f85", wikiTitle: "Absurdní drama" },
  { id: "cermat-postmodernismus", title: "Postmodernismus", start: 1960, end: 2000, row: 3, scope: "world", color: "#4f7b8d", wikiTitle: "Postmodernismus" },
  { id: "cermat-majovci", title: "Májovci", start: 1858, end: 1870, row: 2, scope: "czech", color: "#6b87aa", wikiTitle: "Májovci" },
  { id: "cermat-ruchovci", title: "Ruchovci", start: 1868, end: 1890, row: 2, scope: "czech", color: "#8a6b4f", wikiTitle: "Ruchovci" },
  { id: "cermat-lumirovci", title: "Lumírovci", start: 1877, end: 1895, row: 2, scope: "czech", color: "#765d9a", wikiTitle: "Lumírovci" },
  { id: "cermat-ceska-moderna", title: "Česká moderna", start: 1895, end: 1910, row: 2, scope: "czech", color: "#477c85", wikiTitle: "Česká moderna" },
  { id: "cermat-burici", title: "Generace buřičů", start: 1895, end: 1914, row: 2, scope: "czech", color: "#a85a4d", wikiTitle: "Anarchističtí buřiči" },
  { id: "cermat-devetsil", title: "Devětsil", start: 1920, end: 1931, row: 2, scope: "czech", color: "#477b9a", wikiTitle: "Devětsil" },
  { id: "cermat-skupina42", title: "Skupina 42", start: 1942, end: 1948, row: 2, scope: "czech", color: "#676e78", wikiTitle: "Skupina 42" },
  { id: "cermat-prokleti", title: "Prokletí básníci", start: 1860, end: 1890, row: 3, scope: "world", color: "#78527b", wikiTitle: "Prokletí básníci" },
  { id: "cermat-lost-generation", title: "Ztracená generace", start: 1918, end: 1940, row: 3, scope: "world", color: "#8a6650", wikiTitle: "Ztracená generace" },
  { id: "cermat-beat-generation", title: "Beat generation", start: 1950, end: 1965, row: 3, scope: "world", color: "#4e7b6a", wikiTitle: "Beat generation" },
];

const n = (value: string) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, " ").trim();
const authorTitles = new Set(AUTHORS.map((item) => n(item.title)));
CURRICULUM_AUTHORS.forEach((item) => { if (!authorTitles.has(n(item.title))) { AUTHORS.push(item); authorTitles.add(n(item.title)); } });
const workKeys = new Set(WORKS.map((item) => `${n(item.title)}::${item.authorId || ""}`));
CURRICULUM_WORKS.forEach((item) => { const key = `${n(item.title)}::${item.authorId || ""}`; if (!workKeys.has(key)) { WORKS.push(item); workKeys.add(key); } });
const periodTitles = new Set(PERIODS.map((item) => n(item.title)));
CURRICULUM_PERIODS.forEach((item) => { if (!periodTitles.has(n(item.title))) { PERIODS.push(item); periodTitles.add(n(item.title)); } });

export const PRIMMAT_AUTHOR_TITLES = ["Giovanni Boccaccio", "William Shakespeare", "Daniel Defoe", "Denis Diderot", "Molière", "Jane Austenová", "Honoré de Balzac", "Charles Baudelaire", "Karel Jaromír Erben", "Karel Hynek Mácha", "Gustave Flaubert", "Nikolaj Vasiljevič Gogol", "Karel Havlíček Borovský", "Alois Jirásek", "Alois Mrštík", "Vilém Mrštík", "Guy de Maupassant", "Božena Němcová", "Jan Neruda", "Edgar Allan Poe", "Alexandr Sergejevič Puškin", "Josef Karel Šlejhar", "Henrik Ibsen", "Oscar Wilde", "Émile Zola", "Samuel Beckett", "Paulo Coelho", "Antoine de Saint-Exupéry", "Francis Scott Fitzgerald", "Anne Franková", "Ernest Hemingway", "Franz Kafka", "Jack Kerouac", "Robert Merle", "Vladimir Nabokov", "George Orwell", "Erich Maria Remarque", "Romain Rolland", "J. D. Salinger", "John Steinbeck", "William Styron", "J. R. R. Tolkien", "Viktor Dyk", "Vladislav Vančura", "Karel Poláček", "Michal Viewegh", "Petr Bezruč", "Karel Čapek", "Ladislav Fuks", "Bohumil Hrabal", "Milan Kundera", "Květa Legátová", "Arnošt Lustig", "Vítězslav Nezval", "Ota Pavel", "Ivan Olbracht", "Josef Škvorecký", "Alena Mornštajnová", "Karin Lednická"] as const;
export const CERMAT_MOVEMENTS = ["Antika", "Středověk", "Renesance a humanismus", "Baroko", "Klasicismus a osvícenství", "Preromantismus a romantismus", "Realismus a naturalismus", "Literární moderna", "Modernismus a avantgarda", "Existencialismus", "Socialistický realismus", "Magický realismus", "Absurdní drama", "Postmodernismus", "Májovci", "Ruchovci", "Lumírovci", "Česká moderna", "Generace buřičů", "Devětsil", "Skupina 42", "Prokletí básníci", "Ztracená generace", "Beat generation"] as const;
export const CERMAT_GENRES = ["anekdota", "bajka", "balada", "cestopis", "elegie", "epigram", "epos", "fantasy", "kaligram", "komedie", "kronika", "legenda", "mýtus", "novela", "óda", "pásmo", "píseň", "poema", "pohádka", "pověst", "povídka", "román", "sci-fi", "sonet", "romance", "tragédie"] as const;