export type LaneId =
  | "authors"
  | "works"
  | "rulers"
  | "czech"
  | "world"
  | "tech"
  | "monuments"
  | "figures";

export type TimelineKind = "author" | "work" | "event" | "period";

export interface TimelineItem {
  id: string;
  title: string;
  start: number;
  end: number;
  lane: LaneId;
  kind: TimelineKind;
  importance: 1 | 2 | 3 | 4 | 5;
  summary: string;
  wikiTitle: string;
  authorId?: string;
  living?: boolean;
  color?: string;
  tags?: string[];
}

export interface Period {
  id: string;
  title: string;
  start: number;
  end: number;
  row: number;
  scope: "world" | "czech";
  color: string;
  wikiTitle: string;
}

const author = (
  id: string,
  title: string,
  start: number,
  end: number,
  wikiTitle: string,
  summary: string,
  living = false,
): TimelineItem => ({
  id,
  title,
  start,
  end,
  lane: "authors",
  kind: "author",
  importance: 5,
  summary,
  wikiTitle,
  living,
});

const work = (
  id: string,
  authorId: string,
  title: string,
  year: number,
  wikiTitle: string,
): TimelineItem => ({
  id,
  authorId,
  title,
  start: year,
  end: year,
  lane: "works",
  kind: "work",
  importance: 4,
  summary: "Literární dílo.",
  wikiTitle,
});

const event = (
  id: string,
  title: string,
  start: number,
  end: number,
  lane: Exclude<LaneId, "authors" | "works">,
  importance: 1 | 2 | 3 | 4 | 5,
  wikiTitle: string,
  summary: string,
  tags: string[] = [],
): TimelineItem => ({
  id,
  title,
  start,
  end,
  lane,
  kind: "event",
  importance,
  wikiTitle,
  summary,
  tags,
});

export const AUTHORS: TimelineItem[] = [
  author("komensky", "Jan Amos Komenský", 1592, 1670, "Jan Amos Komenský", "Český pedagog, filozof, teolog a spisovatel."),
  author("shakespeare", "William Shakespeare", 1564, 1616, "William Shakespeare", "Anglický dramatik a básník."),
  author("cervantes", "Miguel de Cervantes", 1547, 1616, "Miguel de Cervantes", "Španělský spisovatel, autor Dona Quijota."),
  author("moliere", "Molière", 1622, 1673, "Molière", "Francouzský dramatik a herec."),
  author("defoe", "Daniel Defoe", 1660, 1731, "Daniel Defoe", "Anglický spisovatel a novinář."),
  author("swift", "Jonathan Swift", 1667, 1745, "Jonathan Swift", "Irský satirik a autor Gulliverových cest."),
  author("goethe", "Johann Wolfgang von Goethe", 1749, 1832, "Johann Wolfgang von Goethe", "Německý básník, dramatik a myslitel."),
  author("austen", "Jane Austenová", 1775, 1817, "Jane Austenová", "Anglická autorka společenských románů."),
  author("hugo", "Victor Hugo", 1802, 1885, "Victor Hugo", "Francouzský romantický spisovatel."),
  author("poe", "Edgar Allan Poe", 1809, 1849, "Edgar Allan Poe", "Americký básník a mistr povídky."),
  author("macha", "Karel Hynek Mácha", 1810, 1836, "Karel Hynek Mácha", "Český romantický básník."),
  author("erben", "Karel Jaromír Erben", 1811, 1870, "Karel Jaromír Erben", "Český básník a sběratel lidové slovesnosti."),
  author("dickens", "Charles Dickens", 1812, 1870, "Charles Dickens", "Anglický romanopisec viktoriánské éry."),
  author("borovsky", "Karel Havlíček Borovský", 1821, 1856, "Karel Havlíček Borovský", "Český novinář, básník a satirik."),
  author("dostoevsky", "Fjodor Michajlovič Dostojevskij", 1821, 1881, "Fjodor Michajlovič Dostojevskij", "Ruský romanopisec a psychologický prozaik."),
  author("tolstoy", "Lev Nikolajevič Tolstoj", 1828, 1910, "Lev Nikolajevič Tolstoj", "Ruský romanopisec a myslitel."),
  author("verne", "Jules Verne", 1828, 1905, "Jules Verne", "Francouzský autor dobrodružné a vědeckofantastické literatury."),
  author("twain", "Mark Twain", 1835, 1910, "Mark Twain", "Americký humorista a spisovatel."),
  author("wilde", "Oscar Wilde", 1854, 1900, "Oscar Wilde", "Irský dramatik, prozaik a estét."),
  author("rolland", "Romain Rolland", 1866, 1944, "Romain Rolland", "Francouzský spisovatel a nositel Nobelovy ceny."),
  author("kafka", "Franz Kafka", 1883, 1924, "Franz Kafka", "Pražský německy píšící prozaik."),
  author("woolf", "Virginia Woolfová", 1882, 1941, "Virginia Woolfová", "Britská modernistická spisovatelka."),
  author("capek", "Karel Čapek", 1890, 1938, "Karel Čapek", "Český spisovatel, dramatik a novinář."),
  author("tolkien", "J. R. R. Tolkien", 1892, 1973, "J. R. R. Tolkien", "Britský spisovatel a filolog."),
  author("hemingway", "Ernest Hemingway", 1899, 1961, "Ernest Hemingway", "Americký prozaik a nositel Nobelovy ceny."),
  author("remarque", "Erich Maria Remarque", 1898, 1970, "Erich Maria Remarque", "Německý autor protiválečné prózy."),
  author("nezval", "Vítězslav Nezval", 1900, 1958, "Vítězslav Nezval", "Český básník poetismu a surrealismu."),
  author("steinbeck", "John Steinbeck", 1902, 1968, "John Steinbeck", "Americký prozaik a nositel Nobelovy ceny."),
  author("orwell", "George Orwell", 1903, 1950, "George Orwell", "Britský prozaik a esejista."),
  author("beckett", "Samuel Beckett", 1906, 1989, "Samuel Beckett", "Irský dramatik a prozaik absurdního divadla."),
  author("camus", "Albert Camus", 1913, 1960, "Albert Camus", "Francouzský spisovatel a filozof existencialismu."),
  author("anne-frank", "Anne Franková", 1929, 1945, "Anne Franková", "Autorka deníku z období holokaustu."),
  author("kundera", "Milan Kundera", 1929, 2023, "Milan Kundera", "Česko-francouzský romanopisec."),
  author("ota-pavel", "Ota Pavel", 1930, 1973, "Ota Pavel", "Český prozaik a sportovní novinář."),
  author("marquez", "Gabriel García Márquez", 1927, 2014, "Gabriel García Márquez", "Kolumbijský autor magického realismu."),
  author("king", "Stephen King", 1947, 2026, "Stephen King", "Americký autor hororu a fantastiky.", true),
  author("coelho", "Paulo Coelho", 1947, 2026, "Paulo Coelho", "Brazilský romanopisec.", true),
  author("murakami", "Haruki Murakami", 1949, 2026, "Haruki Murakami", "Japonský romanopisec a esejista.", true),
  author("rowling", "J. K. Rowlingová", 1965, 2026, "J. K. Rowlingová", "Britská autorka série Harry Potter.", true),
  author("mornstajnova", "Alena Mornštajnová", 1963, 2026, "Alena Mornštajnová", "Současná česká spisovatelka.", true),
];

export const WORKS: TimelineItem[] = [
  work("labyrint", "komensky", "Labyrint světa a ráj srdce", 1631, "Labyrint světa a ráj srdce"),
  work("didactica", "komensky", "Velká didaktika", 1657, "Didactica magna"),
  work("orbis", "komensky", "Orbis pictus", 1658, "Orbis pictus"),
  work("romeo", "shakespeare", "Romeo a Julie", 1597, "Romeo a Julie"),
  work("hamlet", "shakespeare", "Hamlet", 1603, "Hamlet"),
  work("macbeth", "shakespeare", "Macbeth", 1606, "Macbeth"),
  work("don-quijote", "cervantes", "Důmyslný rytíř Don Quijote de la Mancha", 1605, "Důmyslný rytíř Don Quijote de la Mancha"),
  work("tartuffe", "moliere", "Tartuffe", 1664, "Tartuffe"),
  work("misanthrope", "moliere", "Misantrop", 1666, "Misantrop"),
  work("robinson", "defoe", "Robinson Crusoe", 1719, "Robinson Crusoe"),
  work("gulliver", "swift", "Gulliverovy cesty", 1726, "Gulliverovy cesty"),
  work("werther", "goethe", "Utrpení mladého Werthera", 1774, "Utrpení mladého Werthera"),
  work("faust", "goethe", "Faust", 1808, "Faust (Goethe)"),
  work("pride", "austen", "Pýcha a předsudek", 1813, "Pýcha a předsudek"),
  work("emma", "austen", "Emma", 1815, "Emma (román)"),
  work("notre-dame", "hugo", "Chrám Matky Boží v Paříži", 1831, "Chrám Matky Boží v Paříži"),
  work("les-mis", "hugo", "Bídníci", 1862, "Bídníci"),
  work("pit", "poe", "Jáma a kyvadlo", 1842, "Jáma a kyvadlo"),
  work("raven", "poe", "Havran", 1845, "Havran (báseň)"),
  work("maj", "macha", "Máj", 1836, "Máj (poema)"),
  work("kytice", "erben", "Kytice", 1853, "Kytice (sbírka)"),
  work("oliver", "dickens", "Oliver Twist", 1838, "Oliver Twist"),
  work("great-expectations", "dickens", "Nadějné vyhlídky", 1861, "Nadějné vyhlídky"),
  work("tyrol-elegies", "borovsky", "Tyrolské elegie", 1861, "Tyrolské elegie"),
  work("crime", "dostoevsky", "Zločin a trest", 1866, "Zločin a trest"),
  work("idiot", "dostoevsky", "Idiot", 1869, "Idiot (román)"),
  work("karamazov", "dostoevsky", "Bratři Karamazovi", 1880, "Bratři Karamazovi"),
  work("war-peace", "tolstoy", "Vojna a mír", 1869, "Vojna a mír"),
  work("anna-karenina", "tolstoy", "Anna Kareninová", 1878, "Anna Kareninová"),
  work("20000", "verne", "Dvacet tisíc mil pod mořem", 1870, "Dvacet tisíc mil pod mořem"),
  work("around-world", "verne", "Cesta kolem světa za osmdesát dní", 1872, "Cesta kolem světa za osmdesát dní"),
  work("tom-sawyer", "twain", "Dobrodružství Toma Sawyera", 1876, "Dobrodružství Toma Sawyera"),
  work("huckleberry", "twain", "Dobrodružství Huckleberryho Finna", 1884, "Dobrodružství Huckleberryho Finna"),
  work("dorian", "wilde", "Obraz Doriana Graye", 1890, "Obraz Doriana Graye"),
  work("jean-christophe", "rolland", "Jan Kryštof", 1904, "Jan Kryštof"),
  work("metamorphosis", "kafka", "Proměna", 1915, "Proměna (povídka)"),
  work("trial", "kafka", "Proces", 1925, "Proces (román)"),
  work("castle", "kafka", "Zámek", 1926, "Zámek (román)"),
  work("mrs-dalloway", "woolf", "Paní Dallowayová", 1925, "Paní Dallowayová"),
  work("lighthouse", "woolf", "K majáku", 1927, "K majáku"),
  work("rur", "capek", "R.U.R.", 1920, "R.U.R."),
  work("white-disease", "capek", "Bílá nemoc", 1937, "Bílá nemoc"),
  work("war-salamanders", "capek", "Válka s Mloky", 1936, "Válka s Mloky"),
  work("hobbit", "tolkien", "Hobit", 1937, "Hobit"),
  work("lotr", "tolkien", "Pán prstenů", 1954, "Pán prstenů"),
  work("old-man-sea", "hemingway", "Stařec a moře", 1952, "Stařec a moře"),
  work("western-front", "remarque", "Na západní frontě klid", 1929, "Na západní frontě klid"),
  work("edison", "nezval", "Edison", 1928, "Edison (báseň)"),
  work("mice-men", "steinbeck", "O myších a lidech", 1937, "O myších a lidech"),
  work("grapes", "steinbeck", "Hrozny hněvu", 1939, "Hrozny hněvu"),
  work("animal-farm", "orwell", "Farma zvířat", 1945, "Farma zvířat"),
  work("1984", "orwell", "1984", 1949, "1984 (román)"),
  work("godot", "beckett", "Čekání na Godota", 1953, "Čekání na Godota"),
  work("stranger", "camus", "Cizinec", 1942, "Cizinec (román)"),
  work("anne-diary", "anne-frank", "Deník Anny Frankové", 1947, "Deník Anny Frankové"),
  work("unbearable", "kundera", "Nesnesitelná lehkost bytí", 1984, "Nesnesitelná lehkost bytí"),
  work("smich", "kundera", "Směšné lásky", 1963, "Směšné lásky"),
  work("beautiful-deer", "ota-pavel", "Smrt krásných srnců", 1971, "Smrt krásných srnců"),
  work("solitude", "marquez", "Sto roků samoty", 1967, "Sto roků samoty"),
  work("shining", "king", "Osvícení", 1977, "Osvícení (román)"),
  work("alchemist", "coelho", "Alchymista", 1988, "Alchymista (román)"),
  work("norwegian-wood", "murakami", "Norské dřevo", 1987, "Norské dřevo"),
  work("harry-potter", "rowling", "Harry Potter a Kámen mudrců", 1997, "Harry Potter a Kámen mudrců"),
  work("hana", "mornstajnova", "Hana", 2017, "Hana (román)"),
  work("tiche-roky", "mornstajnova", "Tiché roky", 2019, "Tiché roky"),
];

export const EVENTS: TimelineItem[] = [
  event("ice-age", "Poslední doba ledová", -115000, -9700, "world", 5, "Poslední doba ledová", "Poslední glaciální období.", ["pravěk"]),
  event("neolithic", "Neolitická revoluce", -10000, -3000, "world", 5, "Neolitická revoluce", "Přechod k zemědělství a usedlému způsobu života.", ["pravěk"]),
  event("first-cities", "Vznik prvních měst v Mezopotámii", -4000, -3000, "world", 4, "Mezopotámie", "Rozvoj prvních městských civilizací.", ["starověk"]),
  event("writing", "Vznik klínového písma", -3400, -3200, "tech", 5, "Klínové písmo", "Jeden z nejstarších systémů písma.", ["starověk"]),
  event("egypt", "Sjednocení starověkého Egypta", -3100, -3100, "world", 5, "Starověký Egypt", "Počátek dynastického Egypta.", ["starověk"]),
  event("giza", "Velká pyramida v Gíze", -2580, -2560, "monuments", 5, "Velká pyramida v Gíze", "Jediný dochovaný div antického světa.", ["pyramida", "starověk"]),
  event("hammurabi", "Chammurapiho zákoník", -1754, -1754, "world", 4, "Chammurapiho zákoník", "Jeden z nejznámějších starověkých zákoníků.", ["starověk"]),
  event("olympics", "První doložené olympijské hry", -776, -776, "world", 4, "Antické olympijské hry", "Tradiční rok prvních doložených her.", ["starověk"]),
  event("rome", "Tradiční založení Říma", -753, -753, "world", 4, "Založení Říma", "Tradiční datum založení Říma.", ["starověk"]),
  event("roman-republic", "Římská republika", -509, -27, "world", 5, "Římská republika", "Období římské republiky.", ["starověk"]),
  event("athens", "Vznik athénské demokracie", -508, -508, "world", 4, "Athénská demokracie", "Kleisthenovy reformy.", ["starověk"]),
  event("persian-wars", "Řecko-perské války", -499, -449, "world", 4, "Řecko-perské války", "Války řeckých městských států s Persií.", ["válka", "starověk"]),
  event("alexander", "Tažení Alexandra Velikého", -336, -323, "world", 5, "Alexandr Veliký", "Vznik makedonské říše a šíření helénismu.", ["válka", "starověk"]),
  event("roman-empire", "Římské císařství", -27, 476, "world", 5, "Římské císařství", "Období západního římského císařství.", ["starověk"]),
  event("colosseum", "Výstavba Kolosea", 72, 80, "monuments", 4, "Koloseum", "Velký římský amfiteátr.", ["stavba"]),
  event("pompeii", "Výbuch Vesuvu a zánik Pompejí", 79, 79, "world", 4, "Erupce Vesuvu roku 79", "Erupce pohřbila Pompeje a Herculaneum.", ["starověk"]),
  event("fall-rome", "Pád Západořímské říše", 476, 476, "world", 5, "Zánik Západořímské říše", "Tradiční konec starověku.", []),
  event("hagia", "Výstavba chrámu Hagia Sofia", 532, 537, "monuments", 4, "Hagia Sofia", "Byzantský chrám v Konstantinopoli.", ["stavba"]),
  event("hijra", "Hidžra", 622, 622, "world", 4, "Hidžra", "Počátek islámského letopočtu.", []),
  event("charlemagne", "Korunovace Karla Velikého", 800, 800, "world", 5, "Karel Veliký", "Korunovace císařem v Římě.", []),
  event("great-moravia", "Velká Morava", 833, 907, "czech", 5, "Velkomoravská říše", "Významný státní útvar západních Slovanů.", []),
  event("cyril", "Příchod Cyrila a Metoděje", 863, 863, "czech", 5, "Cyril a Metoděj", "Byzantská misie na Velké Moravě.", []),
  event("prague-castle", "Založení Pražského hradu", 880, 920, "monuments", 5, "Pražský hrad", "Počátky Pražského hradu.", ["hrad"]),
  event("vysehrad", "Vznik Vyšehradu", 950, 1000, "monuments", 4, "Vyšehrad", "Raně středověké hradiště.", ["hrad"]),
  event("hastings", "Normanské dobytí Anglie", 1066, 1066, "world", 4, "Normanské dobytí Anglie", "Bitva u Hastingsu a nástup Viléma Dobyvatele.", ["válka"]),
  event("crusade", "První křížová výprava", 1096, 1099, "world", 4, "První křížová výprava", "První velká křížová výprava.", ["válka"]),
  event("primda", "Výstavba hradu Přimda", 1121, 1121, "monuments", 4, "Přimda (hrad)", "Jeden z nejstarších kamenných hradů v Česku.", ["hrad"]),
  event("notre-dame", "Výstavba Notre-Dame", 1163, 1345, "monuments", 4, "Notre-Dame (Paříž)", "Výstavba pařížské gotické katedrály.", ["stavba"]),
  event("golden-bull", "Zlatá bula sicilská", 1212, 1212, "czech", 5, "Zlatá bula sicilská", "Potvrzení dědičného královského titulu.", []),
  event("magna-carta", "Magna charta libertatum", 1215, 1215, "world", 4, "Magna charta libertatum", "Listina omezující moc anglického panovníka.", []),
  event("zvikov", "Výstavba hradu Zvíkov", 1230, 1270, "monuments", 4, "Zvíkov (hrad)", "Královský hrad nad soutokem Vltavy a Otavy.", ["hrad"]),
  event("krumlov", "Vznik hradu Český Krumlov", 1240, 1274, "monuments", 4, "Státní hrad a zámek Český Krumlov", "Počátky krumlovského hradního areálu.", ["hrad"]),
  event("karlstejn", "Výstavba Karlštejna", 1348, 1365, "monuments", 5, "Karlštejn", "Hrad založený Karlem IV.", ["hrad"]),
  event("black-death", "Černá smrt v Evropě", 1347, 1351, "world", 5, "Černá smrt", "Morová pandemie zásadně proměnila Evropu.", []),
  event("charles-bridge", "Výstavba Karlova mostu", 1357, 1402, "monuments", 5, "Karlův most", "Výstavba pražského kamenného mostu.", ["stavba"]),
  event("hus", "Upálení mistra Jana Husa", 1415, 1415, "czech", 5, "Upálení mistra Jana Husa", "Smrt Jana Husa v Kostnici.", []),
  event("hussite", "Husitské války", 1419, 1434, "czech", 5, "Husitské války", "Války v českých zemích po smrti Jana Husa.", ["válka"]),
  event("printing", "Vynález knihtisku", 1450, 1450, "tech", 5, "Knihtisk", "Rozšíření evropského knihtisku.", []),
  event("constantinople", "Pád Konstantinopole", 1453, 1453, "world", 5, "Pád Konstantinopole", "Osmanská říše dobyla Konstantinopol.", ["válka"]),
  event("america", "Objevení Ameriky Kryštofem Kolumbem", 1492, 1492, "world", 5, "Objevení Ameriky", "Kolumbova výprava dorazila do Karibiku.", ["objev"]),
  event("reformation", "Začátek reformace", 1517, 1517, "world", 5, "Reformace", "Vystoupení Martina Luthera.", []),
  event("scientific", "Vědecká revoluce", 1543, 1687, "tech", 5, "Vědecká revoluce", "Proměna poznání od Koperníka po Newtona.", []),
  event("defenestration", "Pražská defenestrace", 1618, 1618, "czech", 5, "Pražská defenestrace (1618)", "Událost spojená se začátkem stavovského povstání.", ["válka"]),
  event("thirty-years", "Třicetiletá válka", 1618, 1648, "world", 5, "Třicetiletá válka", "Rozsáhlý evropský konflikt.", ["válka"]),
  event("white-mountain", "Bitva na Bílé hoře", 1620, 1620, "czech", 5, "Bitva na Bílé hoře", "Porážka českého stavovského povstání.", ["válka"]),
  event("taj-mahal", "Výstavba Tádž Mahalu", 1632, 1653, "monuments", 5, "Tádž Mahal", "Mauzoleum vybudované v Ágře.", ["stavba"]),
  event("steam", "Zdokonalení parního stroje", 1769, 1769, "tech", 5, "Parní stroj", "James Watt zdokonalil parní stroj.", []),
  event("american-revolution", "Americká revoluce", 1775, 1783, "world", 5, "Americká revoluce", "Vznik Spojených států amerických.", ["válka"]),
  event("toleration", "Toleranční patent a zrušení nevolnictví", 1781, 1781, "czech", 5, "Toleranční patent", "Reformy Josefa II.", []),
  event("french-revolution", "Francouzská revoluce", 1789, 1799, "world", 5, "Velká francouzská revoluce", "Zásadní politická a společenská revoluce.", []),
  event("napoleonic", "Napoleonské války", 1803, 1815, "world", 5, "Napoleonské války", "Série evropských konfliktů.", ["válka"]),
  event("vienna", "Vídeňský kongres", 1814, 1815, "world", 4, "Vídeňský kongres", "Uspořádání Evropy po napoleonských válkách.", []),
  event("revolution-1848", "Revoluční rok 1848", 1848, 1849, "czech", 5, "Revoluce v Rakouském císařství 1848–1849", "Revoluční události v českých zemích a monarchii.", []),
  event("national-theatre", "Výstavba Národního divadla", 1868, 1883, "monuments", 5, "Národní divadlo", "Výstavba a znovuotevření Národního divadla.", ["stavba"]),
  event("telephone", "Vynález telefonu", 1876, 1876, "tech", 4, "Telefon", "Bellův patent telefonu.", []),
  event("bulb", "Praktická elektrická žárovka", 1879, 1879, "tech", 5, "Žárovka", "Rozšíření praktické elektrické žárovky.", []),
  event("eiffel", "Výstavba Eiffelovy věže", 1887, 1889, "monuments", 4, "Eiffelova věž", "Věž pro světovou výstavu v Paříži.", ["stavba"]),
  event("flight", "První motorový let", 1903, 1903, "tech", 5, "Wright Flyer", "První řízený motorový let.", []),
  event("ww1", "První světová válka", 1914, 1918, "world", 5, "První světová válka", "Celosvětový válečný konflikt.", ["válka"]),
  event("czechoslovakia", "Vznik Československa", 1918, 1918, "czech", 5, "Vznik Československa", "Vyhlášení samostatného Československa.", []),
  event("spanish-flu", "Pandemie španělské chřipky", 1918, 1920, "world", 4, "Španělská chřipka", "Celosvětová pandemie.", []),
  event("television", "První veřejný přenos televize", 1926, 1926, "tech", 4, "Televize", "První veřejné demonstrace televize.", []),
  event("depression", "Velká hospodářská krize", 1929, 1939, "world", 5, "Velká hospodářská krize", "Celosvětová hospodářská krize.", []),
  event("munich", "Mnichovská dohoda", 1938, 1938, "czech", 5, "Mnichovská dohoda", "Odstoupení československého pohraničí.", ["válka"]),
  event("ww2", "Druhá světová válka", 1939, 1945, "world", 5, "Druhá světová válka", "Celosvětový válečný konflikt.", ["válka"]),
  event("anthropoid", "Operace Anthropoid", 1941, 1942, "czech", 5, "Operace Anthropoid", "Československý odboj a atentát na Reinharda Heydricha.", ["válka"]),
  event("lidice", "Vyhlazení Lidic", 1942, 1942, "czech", 5, "Vyhlazení Lidic", "Nacistická represivní akce.", ["válka"]),
  event("transistor", "Vynález tranzistoru", 1947, 1947, "tech", 4, "Tranzistor", "Zásadní součást moderní elektroniky.", []),
  event("february", "Komunistický převrat v Československu", 1948, 1948, "czech", 5, "Únor 1948", "Převzetí moci Komunistickou stranou Československa.", []),
  event("dna", "Objev struktury DNA", 1953, 1953, "tech", 5, "DNA", "Popsání dvojšroubovicové struktury DNA.", []),
  event("integrated-circuit", "Integrovaný obvod", 1958, 1958, "tech", 4, "Integrovaný obvod", "Základ moderní mikroelektroniky.", []),
  event("berlin-wall", "Berlínská zeď", 1961, 1989, "world", 5, "Berlínská zeď", "Symbol rozdělení Evropy během studené války.", []),
  event("prague-spring", "Pražské jaro a invaze", 1968, 1968, "czech", 5, "Invaze vojsk Varšavské smlouvy do Československa", "Reformní proces a následná invaze.", ["válka"]),
  event("moon", "První člověk na Měsíci", 1969, 1969, "world", 5, "Apollo 11", "Přistání mise Apollo 11 na Měsíci.", []),
  event("arpanet", "Vznik sítě ARPANET", 1969, 1969, "tech", 5, "ARPANET", "Předchůdce internetu.", []),
  event("velvet", "Sametová revoluce", 1989, 1989, "czech", 5, "Sametová revoluce", "Pád komunistického režimu v Československu.", []),
  event("web", "Vznik World Wide Webu", 1989, 1991, "tech", 5, "World Wide Web", "Tim Berners-Lee vytvořil základy webu.", []),
  event("czech-republic", "Vznik České republiky", 1993, 1993, "czech", 5, "Vznik České republiky", "Rozdělení Československa.", []),
  event("eu", "Vstup České republiky do Evropské unie", 2004, 2004, "czech", 4, "Vstup Česka do Evropské unie", "Česká republika vstoupila do EU.", []),
  event("iphone", "Představení prvního iPhonu", 2007, 2007, "tech", 4, "iPhone (1. generace)", "Představení prvního iPhonu.", []),
  event("financial-crisis", "Globální finanční krize", 2007, 2009, "world", 4, "Světová finanční krize 2008", "Globální finanční a hospodářská krize.", []),
  event("crispr", "Genové editování CRISPR-Cas9", 2012, 2012, "tech", 4, "CRISPR", "Rozvoj přesné genové editace.", []),
  event("covid", "Pandemie covidu-19", 2020, 2023, "world", 5, "Pandemie covidu-19", "Celosvětová pandemie.", []),
  event("ukraine", "Ruská invaze na Ukrajinu", 2022, 2026, "world", 5, "Ruská invaze na Ukrajinu", "Rozsáhlá ruská invaze zahájená v únoru 2022.", ["válka"]),
];

export const FIGURES: TimelineItem[] = [
  event("socrates", "Sókratés", -470, -399, "figures", 5, "Sókratés", "Řecký filozof.", ["filozofie"]),
  event("aristotle", "Aristotelés", -384, -322, "figures", 5, "Aristotelés", "Filozof a učenec.", ["filozofie", "věda"]),
  event("caesar", "Julius Caesar", -100, -44, "figures", 5, "Julius Caesar", "Římský vojevůdce a politik.", []),
  event("cleopatra", "Kleopatra VII.", -69, -30, "figures", 4, "Kleopatra VII.", "Panovnice ptolemaiovského Egypta.", []),
  event("charles-great", "Karel Veliký", 748, 814, "figures", 5, "Karel Veliký", "Franský král a císař.", []),
  event("leonardo", "Leonardo da Vinci", 1452, 1519, "figures", 5, "Leonardo da Vinci", "Renesanční umělec, konstruktér a učenec.", []),
  event("columbus", "Kryštof Kolumbus", 1451, 1506, "figures", 5, "Kryštof Kolumbus", "Mořeplavec spojený s objevením Ameriky.", []),
  event("copernicus", "Mikuláš Koperník", 1473, 1543, "figures", 5, "Mikuláš Koperník", "Astronom heliocentrického modelu.", []),
  event("galileo", "Galileo Galilei", 1564, 1642, "figures", 5, "Galileo Galilei", "Astronom a fyzik.", []),
  event("newton", "Isaac Newton", 1643, 1727, "figures", 5, "Isaac Newton", "Fyzik a matematik.", []),
  event("darwin", "Charles Darwin", 1809, 1882, "figures", 5, "Charles Darwin", "Přírodovědec evoluční teorie.", []),
  event("tesla", "Nikola Tesla", 1856, 1943, "figures", 5, "Nikola Tesla", "Vynálezce a elektrotechnik.", []),
  event("curie", "Marie Curie-Skłodowská", 1867, 1934, "figures", 5, "Marie Curie-Skłodowská", "Průkopnice výzkumu radioaktivity.", []),
  event("einstein", "Albert Einstein", 1879, 1955, "figures", 5, "Albert Einstein", "Fyzik teorie relativity.", []),
  event("turing", "Alan Turing", 1912, 1954, "figures", 5, "Alan Turing", "Matematik a průkopník informatiky.", []),
];

export const RULERS: TimelineItem[] = [
  event("karel-iv", "Karel IV.", 1346, 1378, "rulers", 5, "Karel IV.", "Český král a římský císař."),
  event("vaclav-iv", "Václav IV.", 1378, 1419, "rulers", 4, "Václav IV.", "Český král."),
  event("zikmund", "Zikmund Lucemburský", 1419, 1437, "rulers", 5, "Zikmund Lucemburský", "Český král a římský císař."),
  event("jiri", "Jiří z Poděbrad", 1458, 1471, "rulers", 5, "Jiří z Poděbrad", "Český král."),
  event("vladislav", "Vladislav II. Jagellonský", 1471, 1516, "rulers", 4, "Vladislav Jagellonský", "Český a uherský král."),
  event("ferdinand-i", "Ferdinand I. Habsburský", 1526, 1564, "rulers", 4, "Ferdinand I. Habsburský", "Český král."),
  event("rudolf-ii", "Rudolf II.", 1576, 1611, "rulers", 5, "Rudolf II.", "Císař a český král."),
  event("ferdinand-ii", "Ferdinand II.", 1617, 1637, "rulers", 4, "Ferdinand II. Štýrský", "Český král a císař."),
  event("leopold-i", "Leopold I.", 1657, 1705, "rulers", 4, "Leopold I.", "Český král a císař."),
  event("louis-xiv", "Ludvík XIV.", 1643, 1715, "rulers", 5, "Ludvík XIV.", "Francouzský král."),
  event("marie-terezie", "Marie Terezie", 1740, 1780, "rulers", 5, "Marie Terezie", "Česká a uherská královna."),
  event("josef-ii", "Josef II.", 1780, 1790, "rulers", 5, "Josef II.", "Císař a reformátor."),
  event("napoleon", "Napoleon Bonaparte", 1804, 1815, "rulers", 5, "Napoleon Bonaparte", "Francouzský císař."),
  event("franz-josef", "František Josef I.", 1848, 1916, "rulers", 5, "František Josef I.", "Rakouský císař a český král."),
  event("masaryk", "Tomáš Garrigue Masaryk", 1918, 1935, "rulers", 5, "Tomáš Garrigue Masaryk", "První československý prezident."),
  event("benes", "Edvard Beneš", 1935, 1948, "rulers", 5, "Edvard Beneš", "Československý prezident."),
  event("hacha", "Emil Hácha", 1938, 1945, "rulers", 4, "Emil Hácha", "Prezident a státní prezident."),
  event("gottwald", "Klement Gottwald", 1948, 1953, "rulers", 5, "Klement Gottwald", "Československý prezident."),
  event("zapadotocky", "Antonín Zápotocký", 1953, 1957, "rulers", 3, "Antonín Zápotocký", "Československý prezident."),
  event("novotny", "Antonín Novotný", 1957, 1968, "rulers", 4, "Antonín Novotný", "Československý prezident."),
  event("svoboda", "Ludvík Svoboda", 1968, 1975, "rulers", 4, "Ludvík Svoboda", "Československý prezident."),
  event("husak", "Gustáv Husák", 1975, 1989, "rulers", 5, "Gustáv Husák", "Československý prezident."),
  event("havel-cs", "Václav Havel", 1989, 1992, "rulers", 5, "Václav Havel", "Československý prezident."),
  event("havel-cz", "Václav Havel", 1993, 2003, "rulers", 5, "Václav Havel", "Český prezident."),
  event("klaus", "Václav Klaus", 2003, 2013, "rulers", 4, "Václav Klaus", "Český prezident."),
  event("zeman", "Miloš Zeman", 2013, 2023, "rulers", 4, "Miloš Zeman", "Český prezident."),
  event("pavel", "Petr Pavel", 2023, 2026, "rulers", 5, "Petr Pavel", "Současný prezident České republiky."),
];

export const PERIODS: Period[] = [
  { id: "stone-age", title: "Pozdní doba kamenná", start: -12000, end: -3000, row: 0, scope: "world", color: "#a99167", wikiTitle: "Doba kamenná" },
  { id: "ancient", title: "Starověk", start: -3000, end: 476, row: 0, scope: "world", color: "#c89b4d", wikiTitle: "Starověk" },
  { id: "middle-ages", title: "Středověk", start: 476, end: 1492, row: 0, scope: "world", color: "#8874aa", wikiTitle: "Středověk" },
  { id: "early-modern", title: "Raný novověk", start: 1492, end: 1789, row: 0, scope: "world", color: "#d38d55", wikiTitle: "Raný novověk" },
  { id: "modern", title: "Moderní dějiny", start: 1789, end: 1914, row: 0, scope: "world", color: "#6e9aaa", wikiTitle: "Moderní dějiny" },
  { id: "contemporary", title: "Soudobé dějiny", start: 1914, end: 2026, row: 0, scope: "world", color: "#6d82b0", wikiTitle: "Soudobé dějiny" },
  { id: "renaissance", title: "Renesance", start: 1400, end: 1600, row: 1, scope: "world", color: "#d49c4f", wikiTitle: "Renesance" },
  { id: "baroque", title: "Baroko", start: 1600, end: 1750, row: 1, scope: "world", color: "#ae6888", wikiTitle: "Baroko" },
  { id: "enlightenment", title: "Osvícenství", start: 1685, end: 1815, row: 1, scope: "world", color: "#c5ae48", wikiTitle: "Osvícenství" },
  { id: "industrial", title: "Průmyslová revoluce", start: 1760, end: 1840, row: 1, scope: "world", color: "#6e9aaa", wikiTitle: "Průmyslová revoluce" },
  { id: "great-moravia-period", title: "Velká Morava", start: 833, end: 907, row: 2, scope: "czech", color: "#4f9275", wikiTitle: "Velkomoravská říše" },
  { id: "premyslid", title: "Přemyslovský stát", start: 895, end: 1306, row: 2, scope: "czech", color: "#5e8dad", wikiTitle: "Přemyslovci" },
  { id: "luxembourg", title: "Lucemburkové", start: 1310, end: 1437, row: 2, scope: "czech", color: "#765e9d", wikiTitle: "Lucemburkové" },
  { id: "hussite-period", title: "Husitské období", start: 1419, end: 1434, row: 2, scope: "czech", color: "#b45f52", wikiTitle: "Husitské války" },
  { id: "habsburg", title: "Habsburská monarchie", start: 1526, end: 1804, row: 2, scope: "czech", color: "#5479b4", wikiTitle: "Habsburská monarchie" },
  { id: "revival", title: "Národní obrození", start: 1775, end: 1850, row: 2, scope: "czech", color: "#3e8f73", wikiTitle: "České národní obrození" },
  { id: "austria-hungary", title: "Rakousko-Uhersko", start: 1867, end: 1918, row: 2, scope: "czech", color: "#c69b2e", wikiTitle: "Rakousko-Uhersko" },
  { id: "first-republic", title: "První republika", start: 1918, end: 1938, row: 2, scope: "czech", color: "#699fc5", wikiTitle: "První republika" },
  { id: "protectorate", title: "Protektorát Čechy a Morava", start: 1939, end: 1945, row: 2, scope: "czech", color: "#9a76b0", wikiTitle: "Protektorát Čechy a Morava" },
  { id: "communism", title: "Komunistické Československo", start: 1948, end: 1989, row: 2, scope: "czech", color: "#c65d79", wikiTitle: "Komunistický režim v Československu" },
  { id: "czech-republic-period", title: "Česká republika", start: 1993, end: 2026, row: 2, scope: "czech", color: "#58a877", wikiTitle: "Česko" },
];

export const DEFAULT_AUTHOR_IDS = [
  "rolland",
  "kafka",
  "capek",
  "remarque",
  "nezval",
  "steinbeck",
  "orwell",
  "beckett",
  "anne-frank",
  "kundera",
  "ota-pavel",
  "coelho",
  "mornstajnova",
];

export const LANE_META: Record<LaneId, { label: string; color: string }> = {
  authors: { label: "Autoři", color: "#7a4f9d" },
  works: { label: "Díla", color: "#9b6fc0" },
  rulers: { label: "Vládci a prezidenti", color: "#a97a2f" },
  czech: { label: "České dějiny", color: "#4f6f9a" },
  world: { label: "Svět a války", color: "#a84e46" },
  tech: { label: "Vynálezy a věda", color: "#b4842e" },
  monuments: { label: "Stavby a hrady", color: "#87633f" },
  figures: { label: "Významné osobnosti", color: "#397f78" },
};

export const ALL_ITEMS = [...AUTHORS, ...WORKS, ...RULERS, ...EVENTS, ...FIGURES];
