import type { Period, TimelineItem } from "./data";

const event = (
  id: string,
  title: string,
  start: number,
  end: number,
  lane: TimelineItem["lane"],
  importance: TimelineItem["importance"],
  wikiTitle: string,
  summary: string,
  tags: string[] = [],
): TimelineItem => ({
  id,
  title,
  start,
  end,
  lane,
  kind: "event",
  importance,
  wikiTitle,
  summary,
  tags,
});

export const EXTRA_EVENTS: TimelineItem[] = [
  event("extra-parthenon", "Výstavba Parthenónu", -447, -432, "monuments", 5, "Parthenón", "Vrcholné dílo klasické řecké architektury.", ["starověk", "stavba"]),
  event("extra-pantheon", "Výstavba římského Pantheonu", 118, 128, "monuments", 4, "Pantheon (Řím)", "Jeden z nejlépe dochovaných chrámů antického Říma.", ["starověk", "stavba"]),
  event("extra-justinian", "Justiniánův zákoník", 529, 534, "world", 4, "Corpus iuris civilis", "Kodifikace římského práva za císaře Justiniána I.", ["středověk", "právo"]),
  event("extra-samo", "Sámova říše", 623, 658, "czech", 4, "Sámova říše", "První známý nadkmenový útvar Slovanů ve střední Evropě.", ["Česko", "raný středověk"]),
  event("extra-borivoj", "Křest knížete Bořivoje I.", 883, 883, "czech", 4, "Bořivoj I.", "Přijetí křesťanství přemyslovským knížetem Bořivojem I.", ["Česko", "křesťanství"]),
  event("extra-vaclav", "Smrt knížete Václava", 935, 935, "czech", 4, "Svatý Václav", "Zavraždění knížete Václava ve Staré Boleslavi.", ["Česko"]),
  event("extra-bishopric", "Založení pražského biskupství", 973, 973, "czech", 4, "Pražské biskupství", "Vznik samostatného pražského biskupství.", ["Česko", "církev"]),
  event("extra-premysl-king", "Přemysl Otakar I. získal královský titul", 1198, 1198, "czech", 4, "Přemysl Otakar I.", "Upevnění dědičného královského postavení českých panovníků.", ["Česko"]),
  event("extra-marchfeld", "Bitva na Moravském poli", 1278, 1278, "czech", 5, "Bitva na Moravském poli", "Porážka a smrt Přemysla Otakara II.", ["Česko", "válka"]),
  event("extra-charles-university", "Založení Univerzity Karlovy", 1348, 1348, "czech", 5, "Univerzita Karlova", "Karel IV. založil první univerzitu ve střední Evropě severně od Alp.", ["Česko", "vzdělávání"]),
  event("extra-st-vitus", "Výstavba katedrály sv. Víta", 1344, 1929, "monuments", 5, "Katedrála svatého Víta, Václava a Vojtěcha", "Pražská katedrála budovaná od gotiky až do 20. století.", ["gotika", "stavba", "Česko"]),
  event("extra-st-barbara", "Výstavba chrámu sv. Barbory", 1388, 1905, "monuments", 4, "Chrám svaté Barbory", "Významný gotický chrám v Kutné Hoře.", ["gotika", "stavba", "Česko"]),
  event("extra-kutna-hora-decree", "Dekret kutnohorský", 1409, 1409, "czech", 4, "Dekret kutnohorský", "Změna poměru hlasů na pražské univerzitě ve prospěch českého národa.", ["Česko", "vzdělávání"]),
  event("extra-orloj", "Vznik pražského orloje", 1410, 1410, "monuments", 5, "Staroměstský orloj", "Jeden z nejstarších dochovaných astronomických orlojů na světě.", ["gotika", "věda", "Česko"]),
  event("extra-hundred-years", "Stoletá válka", 1337, 1453, "world", 5, "Stoletá válka", "Dlouhá série konfliktů mezi Anglií a Francií.", ["středověk", "válka"]),
  event("extra-lipany", "Bitva u Lipan", 1434, 1434, "czech", 5, "Bitva u Lipan", "Porážka radikálních husitů a závěr hlavní fáze husitských válek.", ["Česko", "válka"]),
  event("extra-gutenberg-bible", "Vytištění Gutenbergovy bible", 1454, 1455, "tech", 5, "Gutenbergova bible", "Jedna z prvních velkých knih vytištěných evropským knihtiskem.", ["renesance", "knihtisk"]),
  event("extra-gutenberg", "Johannes Gutenberg", 1400, 1468, "figures", 5, "Johannes Gutenberg", "Průkopník evropského knihtisku.", ["renesance", "knihtisk"]),
  event("extra-michelangelo", "Michelangelo Buonarroti", 1475, 1564, "figures", 5, "Michelangelo Buonarroti", "Renesanční sochař, malíř a architekt.", ["renesance", "umění"]),
  event("extra-luther", "Martin Luther", 1483, 1546, "figures", 5, "Martin Luther", "Teolog spojený se začátkem reformace.", ["reformace"]),
  event("extra-vasco", "Vasco da Gama doplul do Indie", 1497, 1498, "world", 4, "Vasco da Gama", "Námořní cesta z Evropy do Indie kolem Afriky.", ["objev", "zámořské objevy"]),
  event("extra-magellan", "První obeplutí Země", 1519, 1522, "world", 5, "Magalhãesova expedice", "První doložená plavba kolem světa.", ["objev", "zámořské objevy"]),
  event("extra-mohacs", "Bitva u Moháče", 1526, 1526, "czech", 5, "Bitva u Moháče", "Smrt Ludvíka Jagellonského a nástup Habsburků na český trůn.", ["Česko", "válka"]),
  event("extra-belveder", "Výstavba Letohrádku královny Anny", 1538, 1565, "monuments", 4, "Letohrádek královny Anny", "Renesanční stavba v areálu Pražského hradu.", ["renesance", "stavba", "Česko"]),
  event("extra-litomysl", "Renesanční přestavba zámku Litomyšl", 1568, 1581, "monuments", 4, "Zámek Litomyšl", "Významný český renesanční zámek.", ["renesance", "stavba", "Česko"]),
  event("extra-rudolfine-prague", "Rudolfínská Praha", 1583, 1611, "czech", 5, "Rudolfínská Praha", "Praha se za Rudolfa II. stala významným centrem vědy a umění.", ["Česko", "renesance", "věda", "umění"]),
  event("extra-komensky", "Jan Amos Komenský", 1592, 1670, "figures", 5, "Jan Amos Komenský", "Český pedagog, filozof, teolog a spisovatel.", ["baroko", "pedagogika", "Česko"]),
  event("extra-descartes", "René Descartes", 1596, 1650, "figures", 4, "René Descartes", "Filozof a matematik raného novověku.", ["filozofie", "věda"]),
  event("extra-old-town-execution", "Staroměstská exekuce", 1621, 1621, "czech", 5, "Staroměstská exekuce", "Poprava představitelů českého stavovského povstání na Staroměstském náměstí.", ["Česko"]),
  event("extra-klementinum", "Výstavba barokního Klementina", 1653, 1726, "monuments", 4, "Klementinum", "Rozsáhlý barokní areál v Praze.", ["baroko", "stavba", "Česko"]),
  event("extra-westphalia", "Vestfálský mír", 1648, 1648, "world", 5, "Vestfálský mír", "Mírové smlouvy ukončily třicetiletou válku.", ["diplomacie"]),
  event("extra-kuks", "Výstavba areálu Kuks", 1694, 1724, "monuments", 4, "Kuks", "Barokní lázeňský a hospitalní komplex.", ["baroko", "stavba", "Česko"]),
  event("extra-st-nicholas", "Výstavba chrámu sv. Mikuláše", 1704, 1755, "monuments", 4, "Kostel svatého Mikuláše (Malá Strana)", "Vrcholná barokní stavba na Malé Straně.", ["baroko", "stavba", "Česko"]),
  event("extra-pragmatic-sanction", "Pragmatická sankce", 1713, 1713, "czech", 4, "Pragmatická sankce", "Nástupnický řád umožnil dědictví habsburských zemí v ženské linii.", ["Česko", "Habsburkové"]),
  event("extra-school-reform", "Zavedení povinné školní docházky", 1774, 1774, "czech", 5, "Všeobecný školní řád", "Školská reforma Marie Terezie zavedla povinnou školní docházku.", ["Česko", "vzdělávání"]),
  event("extra-independence", "Deklarace nezávislosti USA", 1776, 1776, "world", 5, "Deklarace nezávislosti Spojených států amerických", "Vyhlášení nezávislosti třinácti britských kolonií.", ["politika"]),
  event("extra-austerlitz", "Bitva u Slavkova", 1805, 1805, "world", 5, "Bitva u Slavkova", "Napoleonovo vítězství v bitvě tří císařů na Moravě.", ["válka", "Morava"]),
  event("extra-national-museum", "Založení Národního muzea", 1818, 1818, "czech", 4, "Národní muzeum", "Založení instituce pro uchovávání českého kulturního a přírodovědného dědictví.", ["Česko", "kultura"]),
  event("extra-slavic-congress", "Slovanský sjezd v Praze", 1848, 1848, "czech", 4, "Slovanský sjezd v Praze 1848", "Setkání slovanských představitelů během revolučního roku 1848.", ["Česko"]),
  event("extra-hluboka", "Novogotická přestavba zámku Hluboká", 1840, 1871, "monuments", 4, "Hluboká (zámek)", "Novogotická podoba zámku inspirovaná anglickou architekturou.", ["novogotika", "stavba", "Česko"]),
  event("extra-lednice", "Novogotická přestavba zámku Lednice", 1846, 1858, "monuments", 4, "Lednice (zámek)", "Romantická novogotická přestavba lednického zámku.", ["novogotika", "stavba", "Česko"]),
  event("extra-ausgleich", "Rakousko-uherské vyrovnání", 1867, 1867, "czech", 5, "Rakousko-uherské vyrovnání", "Vznik dualistického Rakouska-Uherska.", ["Česko", "Rakousko-Uhersko"]),
  event("extra-abolition-us", "Zrušení otroctví v USA", 1865, 1865, "world", 5, "Třináctý dodatek Ústavy Spojených států amerických", "Ústavní zákaz otroctví ve Spojených státech.", ["lidská práva"]),
  event("extra-german-unification", "Sjednocení Německa", 1871, 1871, "world", 5, "Sjednocení Německa", "Vyhlášení Německého císařství.", ["politika"]),
  event("extra-national-theatre-open", "Otevření Národního divadla", 1881, 1883, "czech", 5, "Národní divadlo", "První otevření, požár a znovuotevření Národního divadla.", ["Česko", "kultura"]),
  event("extra-sagrada", "Výstavba chrámu Sagrada Família", 1882, 2026, "monuments", 4, "Sagrada Família", "Dlouhodobě budovaný chrám Antonia Gaudího v Barceloně.", ["moderní architektura", "stavba"]),
  event("extra-universal-suffrage", "Všeobecné volební právo pro muže", 1907, 1907, "czech", 4, "Volební právo v Předlitavsku", "Zavedení všeobecného a rovného volebního práva pro muže v Předlitavsku.", ["Česko", "politika"]),
  event("extra-czechoslovak-constitution", "Ústava Československé republiky", 1920, 1920, "czech", 5, "Ústavní listina Československé republiky", "Přijetí ústavy první Československé republiky.", ["Česko", "právo"]),
  event("extra-penicillin", "Objev penicilinu", 1928, 1928, "tech", 5, "Penicilin", "Alexander Fleming objevil antibakteriální účinky plísně Penicillium.", ["medicína", "věda"]),
  event("extra-un", "Vznik Organizace spojených národů", 1945, 1945, "world", 5, "Organizace spojených národů", "Založení OSN po druhé světové válce.", ["diplomacie"]),
  event("extra-prague-uprising", "Pražské povstání", 1945, 1945, "czech", 5, "Pražské povstání", "Květnové povstání proti německé okupaci.", ["Česko", "válka"]),
  event("extra-nato", "Vznik NATO", 1949, 1949, "world", 5, "Severoatlantická aliance", "Založení Severoatlantické aliance.", ["studená válka"]),
  event("extra-decolonization", "Dekolonizace Afriky a Asie", 1945, 1975, "world", 4, "Dekolonizace", "Postupný zánik evropských koloniálních říší a vznik nových států.", ["soudobé dějiny"]),
  event("extra-currency-reform", "Měnová reforma v Československu", 1953, 1953, "czech", 5, "Měnová reforma v Československu 1953", "Reforma výrazně znehodnotila úspory obyvatel.", ["Česko", "ekonomika"]),
  event("extra-charter-77", "Charta 77", 1977, 1977, "czech", 5, "Charta 77", "Občanská iniciativa kritizující porušování lidských práv v Československu.", ["Česko", "disent"]),
  event("extra-berlin-wall-fall", "Pád Berlínské zdi", 1989, 1989, "world", 5, "Pád Berlínské zdi", "Symbolický konec rozdělení Berlína a jeden z mezníků konce studené války.", ["studená válka"]),
  event("extra-czech-nato", "Vstup České republiky do NATO", 1999, 1999, "czech", 5, "Vstup České republiky do NATO", "Česká republika se stala členem Severoatlantické aliance.", ["Česko"]),
  event("extra-september-11", "Teroristické útoky 11. září", 2001, 2001, "world", 5, "Teroristické útoky 11. září 2001", "Útoky ve Spojených státech zásadně ovlivnily světovou politiku.", ["soudobé dějiny"]),
  event("extra-direct-election", "První přímá volba prezidenta ČR", 2013, 2013, "czech", 4, "Prezidentské volby v Česku 2013", "První přímá volba českého prezidenta.", ["Česko", "politika"]),
  event("extra-erasmus", "Erasmus Rotterdamský", 1466, 1536, "figures", 4, "Erasmus Rotterdamský", "Humanista, teolog a kritik poměrů pozdního středověku.", ["humanismus"]),
  event("extra-machiavelli", "Niccolò Machiavelli", 1469, 1527, "figures", 4, "Niccolò Machiavelli", "Renesanční politický myslitel a autor Vladaře.", ["renesance", "politika"]),
  event("extra-voltaire", "Voltaire", 1694, 1778, "figures", 5, "Voltaire", "Francouzský osvícenský filozof a spisovatel.", ["osvícenství", "literatura"]),
  event("extra-rousseau", "Jean-Jacques Rousseau", 1712, 1778, "figures", 5, "Jean-Jacques Rousseau", "Filozof osvícenství a autor Společenské smlouvy.", ["osvícenství", "literatura"]),
  event("extra-freud", "Sigmund Freud", 1856, 1939, "figures", 5, "Sigmund Freud", "Zakladatel psychoanalýzy.", ["psychologie"]),
  event("extra-hannah-arendt", "Hannah Arendtová", 1906, 1975, "figures", 4, "Hannah Arendtová", "Politická teoretička zabývající se totalitarismem a moderní společností.", ["filozofie", "soudobé dějiny"]),
];

export const EXTRA_PERIODS: Period[] = [
  { id: "roman-style", title: "Románský sloh", start: 1000, end: 1250, row: 1, scope: "world", color: "#9a7b53", wikiTitle: "Románský sloh" },
  { id: "gothic-style", title: "Gotika", start: 1150, end: 1500, row: 1, scope: "world", color: "#64789d", wikiTitle: "Gotika" },
  { id: "humanism", title: "Humanismus", start: 1350, end: 1600, row: 3, scope: "world", color: "#8d7850", wikiTitle: "Humanismus" },
  { id: "reformation-period", title: "Reformace", start: 1517, end: 1648, row: 1, scope: "world", color: "#9a5d4d", wikiTitle: "Reformace" },
  { id: "rococo", title: "Rokoko", start: 1720, end: 1780, row: 3, scope: "world", color: "#c98ca2", wikiTitle: "Rokoko" },
  { id: "classicism", title: "Klasicismus", start: 1750, end: 1830, row: 1, scope: "world", color: "#a98b55", wikiTitle: "Klasicismus" },
  { id: "romanticism", title: "Romantismus", start: 1790, end: 1850, row: 1, scope: "world", color: "#7f628f", wikiTitle: "Romantismus" },
  { id: "realism", title: "Realismus", start: 1840, end: 1900, row: 3, scope: "world", color: "#6f8066", wikiTitle: "Realismus (umění)" },
  { id: "art-nouveau", title: "Secese", start: 1890, end: 1914, row: 3, scope: "world", color: "#4f8b80", wikiTitle: "Secese" },
  { id: "modernism", title: "Moderna", start: 1890, end: 1945, row: 1, scope: "world", color: "#5f7f83", wikiTitle: "Moderna" },
  { id: "avant-garde", title: "Avantgarda", start: 1910, end: 1940, row: 3, scope: "world", color: "#98654f", wikiTitle: "Avantgarda" },
  { id: "existentialism", title: "Existencialismus", start: 1930, end: 1960, row: 3, scope: "world", color: "#616479", wikiTitle: "Existencialismus" },
];
